/********************************************************************
**       This cc file is generated by program,                     **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: pycrypto.pkg

#include "pycrypto.pybind11.h"


#include "dmrc.hpp"


#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <algorithm>

PYBIND11_MODULE(pycrypto, m) {

    pybind11::class_<CDMRC>(m, "CDMRC")
    .def(pybind11::init<>())
    .def("SetKey", &CDMRC::SetKey)
    .def("SetEncryptKey", &CDMRC::SetEncryptKey)
    .def("SetDecryptKey", &CDMRC::SetDecryptKey)
    .def("Encrypt", &CDMRC::Encrypt)
    .def("Decrypt", &CDMRC::Decrypt);

}
